# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get -y install cmake
          - cmake -B build .
          - cmake --build /opt/atlassian/pipelines/agent/build --config Debug --target all -- -j 4
          - /opt/atlassian/pipelines/agent/build/spacex-launch-parser-test/spacex-launch-parser-test
